// Auto-generated by ts-to-dhi
// Do not edit manually

import { z } from 'dhi';

export const UserSchema = z.object({
  id: z.number(),
  name: z.string(),
  email: z.string(),
  age: z.number().optional(),
  role: z.enum(["admin", "user", "guest"]),
  isActive: z.boolean(),
  metadata: z.any(),
  tags: z.array(z.string()),
  settings: z.record(z.string()),
});

export type User = z.infer<typeof UserSchema>;

export const CreateUserRequestSchema = z.object({
  name: z.string(),
  email: z.string(),
  age: z.number().optional(),
  role: z.enum(["admin", "user"]),
});

export type CreateUserRequest = z.infer<typeof CreateUserRequestSchema>;

export const ApiResponseSchema = z.object({
  success: z.boolean(),
  // data: T (generic parameter - needs manual implementation),
  error: z.string().optional().nullable(),
});

export type ApiResponse = z.infer<typeof ApiResponseSchema>;
