// Auto-generated by ts-to-dhi
// Do not edit manually

import { z } from 'dhi';

export const UserSchema = z.object({
  id: z.number(),
  name: z.string(),
  email: z.string(),
  age: z.number().optional(),
  role: z.enum(["admin", "user", "guest"]),
  isActive: z.boolean(),
  metadata: z.any(),
  tags: z.array(z.string()),
  settings: z.record(z.string()),
});

export type User = z.infer<typeof UserSchema>;

export const CreateUserRequestSchema = z.object({
  name: z.string(),
  email: z.string(),
  age: z.number().optional(),
  role: z.enum(["admin", "user"]),
});

export type CreateUserRequest = z.infer<typeof CreateUserRequestSchema>;

export const ApiResponseSchema = z.object({
  success: z.boolean(),
  // data: T (generic parameter - needs manual implementation),
  error: z.string().optional().nullable(),
});

export type ApiResponse = z.infer<typeof ApiResponseSchema>;

export const PointSchema = z.tuple([z.number(), z.number()]);

export type Point = z.infer<typeof PointSchema>;

export const NamedPointSchema = z.tuple([z.string(), z.number(), z.number()]);

export type NamedPoint = z.infer<typeof NamedPointSchema>;

export const TimestampedSchema = z.object({
  createdAt: z.date(),
  updatedAt: z.date(),
});

export type Timestamped = z.infer<typeof TimestampedSchema>;

export const TimestampedUserSchema = z.intersection([UserSchema, TimestampedSchema]);

export type TimestampedUser = z.infer<typeof TimestampedUserSchema>;

export const DictSchema = z.object({
  // Index signature: [key: string]
  // .catchall(z.number()) would go here but dhi doesn't support it directly
  // Consider using z.record() for this type instead
});

export type Dict = z.infer<typeof DictSchema>;

export const NestedDictSchema = z.object({
  // Index signature: [key: string]
  // .catchall(TSTypeLiteralSchema) would go here but dhi doesn't support it directly
  // Consider using z.record() for this type instead
});

export type NestedDict = z.infer<typeof NestedDictSchema>;
