// Auto-generated by ts-to-dhi
// Do not edit manually

import { z } from 'dhi';

export const ApiClientSchema = z.object({
  baseUrl: z.string(),
  timeout: z.number(),
  // get: () => void (method - validation skipped),
  // post: () => void (method - validation skipped),
  // delete: () => void (method - validation skipped),
});

export type ApiClient = z.infer<typeof ApiClientSchema>;

export const EventEmitterSchema = z.object({
  // on: () => void (method - validation skipped),
  // off: () => void (method - validation skipped),
  // emit: () => void (method - validation skipped),
});

export type EventEmitter = z.infer<typeof EventEmitterSchema>;

export const LoggerSchema = z.object({
  level: z.enum(["debug", "info", "warn", "error"]),
  prefix: z.string().optional(),
  // log: () => void (method - validation skipped),
  // error: () => void (method - validation skipped),
});

export type Logger = z.infer<typeof LoggerSchema>;
