import { describe, it, expect } from "bun:test";
import { generateDhiSchema } from "../src/generator.ts";
import type { ParsedType } from "../src/parser.ts";
describe("generateDhiSchema", () => {
  it("should generate simple object schema", () => {
    const types: ParsedType[] = [{
      name: "User",
      kind: "interface",
      properties: [
        { name: "name", type: "string", optional: false, nullable: false },
        { name: "age", type: "number", optional: false, nullable: false },
      ],
    }];
    
    const output = generateDhiSchema(types);
    
    expect(output).toContain("export const UserSchema = z.object({");
    expect(output).toContain("name: z.string(),");
    expect(output).toContain("age: z.number(),");
    expect(output).toContain("export type User = z.infer<typeof UserSchema>;");
  });

  it("should handle optional properties", () => {
    const types: ParsedType[] = [{
      name: "User",
      kind: "interface",
      properties: [
        { name: "name", type: "string", optional: true, nullable: false },
      ],
    }];
    
    const output = generateDhiSchema(types);
    expect(output).toContain("name: z.string().optional(),");
  });

  it("should handle nullable properties", () => {
    const types: ParsedType[] = [{
      name: "User",
      kind: "interface",
      properties: [
        { name: "name", type: "string", optional: false, nullable: true },
      ],
    }];
    
    const output = generateDhiSchema(types);
    expect(output).toContain("name: z.string().nullable(),");
  });

  it("should handle string literal enums", () => {
    const types: ParsedType[] = [{
      name: "User",
      kind: "interface",
      properties: [
        { name: "role", type: '"admin" | "user"', optional: false, nullable: false },
      ],
    }];
    
    const output = generateDhiSchema(types);
    expect(output).toContain('role: z.enum(["admin", "user"]),');
  });

  it("should handle arrays", () => {
    const types: ParsedType[] = [{
      name: "User",
      kind: "interface",
      properties: [
        { name: "tags", type: "string[]", optional: false, nullable: false },
      ],
    }];
    
    const output = generateDhiSchema(types);
    expect(output).toContain("tags: z.array(z.string()),");
  });

  it("should handle tuples", () => {
    const types: ParsedType[] = [{
      name: "Point",
      kind: "type-alias",
      properties: [],
      rawType: "[number, number]",
    }];
    
    const output = generateDhiSchema(types);
    expect(output).toContain("export const PointSchema = z.tuple([z.number(), z.number()]);");
  });

  it("should handle intersections", () => {
    const types: ParsedType[] = [{
      name: "A",
      kind: "type-alias",
      properties: [],
      rawType: "B & C",
    }];
    
    const output = generateDhiSchema(types);
    expect(output).toContain("z.intersection([BSchema, CSchema])");
  });

  it("should handle Record types", () => {
    const types: ParsedType[] = [{
      name: "User",
      kind: "interface",
      properties: [
        { name: "dict", type: "Record<string, number>", optional: false, nullable: false },
      ],
    }];
    
    const output = generateDhiSchema(types);
    expect(output).toContain("dict: z.record(z.number()),");
  });

  it("should handle method signatures", () => {
    const types: ParsedType[] = [{
      name: "Api",
      kind: "interface",
      properties: [
        { name: "get", type: "() => void", optional: false, nullable: false },
      ],
    }];
    
    const output = generateDhiSchema(types);
    expect(output).toContain("// get: () => void (method - validation skipped),");
  });

  it("should handle generic parameters", () => {
    const types: ParsedType[] = [{
      name: "Response",
      kind: "interface",
      properties: [
        { name: "data", type: "T", optional: false, nullable: false },
      ],
    }];
    
    const output = generateDhiSchema(types);
    expect(output).toContain("// data: T (generic parameter - needs manual implementation),");
  });

  it("should handle multiple types", () => {
    const types: ParsedType[] = [
      { 
        name: "User", 
        kind: "interface", 
        properties: [{ name: "id", type: "number", optional: false, nullable: false }],
      },
      { 
        name: "Address", 
        kind: "interface", 
        properties: [{ name: "street", type: "string", optional: false, nullable: false }],
      },
    ];
    
    const output = generateDhiSchema(types);
    expect(output).toContain("UserSchema");
    expect(output).toContain("AddressSchema");
  });

  it("should handle empty types array", () => {
    const output = generateDhiSchema([]);
    expect(output).toContain("Auto-generated by ts-to-dhi");
    expect(output).not.toContain("z.object");
  });
});
