/**
 * Auto-generated API Client
 * Generated by dhi-sdk from Hono app
 */

import type * as Types from './types';

export interface ClientConfig {
  baseUrl: string;
  headers?: Record<string, string>;
  fetch?: typeof fetch;
}

export interface RequestOptions {
  headers?: Record<string, string>;
  signal?: AbortSignal;
}

export interface ApiResponse<T> {
  data: T;
  status: number;
  headers: Headers;
}

export class ApiError extends Error {
  constructor(
    public status: number,
    public statusText: string,
    public body: unknown
  ) {
    super(`API Error: ${status} ${statusText}`);
    this.name = 'ApiError';
  }
}

export function createClient(config: ClientConfig) {
  const baseUrl = config.baseUrl.replace(/\/$/, '');
  const defaultHeaders = config.headers || {};
  const fetchFn = config.fetch || fetch;

  async function request<T>(
    method: string,
    path: string,
    options: {
      body?: unknown;
      query?: Record<string, string | number | boolean | undefined>;
      headers?: Record<string, string>;
      signal?: AbortSignal;
    } = {}
  ): Promise<ApiResponse<T>> {
    const url = new URL(baseUrl + path);

    if (options.query) {
      for (const [key, value] of Object.entries(options.query)) {
        if (value !== undefined) {
          url.searchParams.set(key, String(value));
        }
      }
    }

    const response = await fetchFn(url.toString(), {
      method,
      headers: {
        'Content-Type': 'application/json',
        ...defaultHeaders,
        ...options.headers,
      },
      body: options.body ? JSON.stringify(options.body) : undefined,
      signal: options.signal,
    });

    if (!response.ok) {
      const body = await response.text().catch(() => null);
      throw new ApiError(response.status, response.statusText, body);
    }

    const data = await response.json() as T;
    return { data, status: response.status, headers: response.headers };
  }

  return {
    root: {
      /**
       * GET /
       */
      async listIndex(options?: RequestOptions): Promise<ApiResponse<Types.GetResponse>> {
        return request<Types.GetResponse>('GET', '/', { ...options });
      },
    },
    health: {
      /**
       * GET /health
       */
      async list(options?: RequestOptions): Promise<ApiResponse<Types.HealthGetResponse>> {
        return request<Types.HealthGetResponse>('GET', '/health', { ...options });
      },
    },
    auth: {
      /**
       * POST /auth/login
       */
      async createLogin(options?: RequestOptions): Promise<ApiResponse<Types.AuthLoginPostResponse>> {
        return request<Types.AuthLoginPostResponse>('POST', '/auth/login', { ...options });
      },
      /**
       * POST /auth/register
       */
      async createRegister(options?: RequestOptions): Promise<ApiResponse<unknown>> {
        return request<unknown>('POST', '/auth/register', { ...options });
      },
      /**
       * POST /auth/refresh
       */
      async createRefresh(options?: RequestOptions): Promise<ApiResponse<Types.AuthRefreshPostResponse>> {
        return request<Types.AuthRefreshPostResponse>('POST', '/auth/refresh', { ...options });
      },
      /**
       * POST /auth/logout
       */
      async createLogout(options?: RequestOptions): Promise<ApiResponse<Types.AuthLogoutPostResponse>> {
        return request<Types.AuthLogoutPostResponse>('POST', '/auth/logout', { ...options });
      },
    },
    users: {
      /**
       * GET /users
       */
      async list(options?: RequestOptions): Promise<ApiResponse<Types.UsersGetResponse>> {
        return request<Types.UsersGetResponse>('GET', '/users', { ...options });
      },
      /**
       * GET /users/:id
       */
      async getUsers(params: Types.UsersGetParams, options?: RequestOptions): Promise<ApiResponse<Types.UsersGetResponse>> {
        return request<Types.UsersGetResponse>('GET', `/users/${params.id}`, { ...options });
      },
      /**
       * PUT /users/:id
       */
      async updateUsers(params: Types.UsersPutParams, options?: RequestOptions): Promise<ApiResponse<Types.UsersPutResponse>> {
        return request<Types.UsersPutResponse>('PUT', `/users/${params.id}`, { ...options });
      },
      /**
       * DELETE /users/:id
       */
      async deleteUsers(params: Types.UsersDeleteParams, options?: RequestOptions): Promise<ApiResponse<Types.UsersDeleteResponse>> {
        return request<Types.UsersDeleteResponse>('DELETE', `/users/${params.id}`, { ...options });
      },
      /**
       * GET /users/:userId/posts
       */
      async getPosts(params: Types.UsersPostsGetParams, options?: RequestOptions): Promise<ApiResponse<Types.UsersPostsGetResponse>> {
        return request<Types.UsersPostsGetResponse>('GET', `/users/${params.userId}/posts`, { ...options });
      },
      /**
       * POST /users/:userId/posts
       */
      async createPosts(params: Types.UsersPostsPostParams, options?: RequestOptions): Promise<ApiResponse<unknown>> {
        return request<unknown>('POST', `/users/${params.userId}/posts`, { ...options });
      },
      /**
       * GET /users/:userId/posts/:postId
       */
      async getPosts(params: Types.UsersPostsGetParams, options?: RequestOptions): Promise<ApiResponse<Types.UsersPostsGetResponse>> {
        return request<Types.UsersPostsGetResponse>('GET', `/users/${params.userId}/posts/${params.postId}`, { ...options });
      },
      /**
       * PUT /users/:userId/posts/:postId
       */
      async updatePosts(params: Types.UsersPostsPutParams, options?: RequestOptions): Promise<ApiResponse<Types.UsersPostsPutResponse>> {
        return request<Types.UsersPostsPutResponse>('PUT', `/users/${params.userId}/posts/${params.postId}`, { ...options });
      },
      /**
       * DELETE /users/:userId/posts/:postId
       */
      async deletePosts(params: Types.UsersPostsDeleteParams, options?: RequestOptions): Promise<ApiResponse<Types.UsersPostsDeleteResponse>> {
        return request<Types.UsersPostsDeleteResponse>('DELETE', `/users/${params.userId}/posts/${params.postId}`, { ...options });
      },
      /**
       * POST /users/:userId/posts/:postId/actions
       */
      async createActions(params: Types.UsersPostsActionsPostParams, options?: RequestOptions): Promise<ApiResponse<Types.UsersPostsActionsPostResponse>> {
        return request<Types.UsersPostsActionsPostResponse>('POST', `/users/${params.userId}/posts/${params.postId}/actions`, { ...options });
      },
      /**
       * GET /users/:userId/posts/:postId/comments
       */
      async getComments(params: Types.UsersPostsCommentsGetParams, options?: RequestOptions): Promise<ApiResponse<Types.UsersPostsCommentsGetResponse>> {
        return request<Types.UsersPostsCommentsGetResponse>('GET', `/users/${params.userId}/posts/${params.postId}/comments`, { ...options });
      },
      /**
       * POST /users/:userId/posts/:postId/comments
       */
      async createComments(params: Types.UsersPostsCommentsPostParams, options?: RequestOptions): Promise<ApiResponse<unknown>> {
        return request<unknown>('POST', `/users/${params.userId}/posts/${params.postId}/comments`, { ...options });
      },
      /**
       * DELETE /users/:userId/posts/:postId/comments/:commentId
       */
      async deleteComments(params: Types.UsersPostsCommentsDeleteParams, options?: RequestOptions): Promise<ApiResponse<Types.UsersPostsCommentsDeleteResponse>> {
        return request<Types.UsersPostsCommentsDeleteResponse>('DELETE', `/users/${params.userId}/posts/${params.postId}/comments/${params.commentId}`, { ...options });
      },
    },
    moderation: {
      /**
       * POST /moderation/posts/:postId
       */
      async createPosts(params: Types.ModerationPostsPostParams, options?: RequestOptions): Promise<ApiResponse<Types.ModerationPostsPostResponse>> {
        return request<Types.ModerationPostsPostResponse>('POST', `/moderation/posts/${params.postId}`, { ...options });
      },
      /**
       * POST /moderation/comments/:commentId
       */
      async createComments(params: Types.ModerationCommentsPostParams, options?: RequestOptions): Promise<ApiResponse<Types.ModerationCommentsPostResponse>> {
        return request<Types.ModerationCommentsPostResponse>('POST', `/moderation/comments/${params.commentId}`, { ...options });
      },
      /**
       * POST /moderation/users/:userId
       */
      async createUsers(params: Types.ModerationUsersPostParams, options?: RequestOptions): Promise<ApiResponse<Types.ModerationUsersPostResponse>> {
        return request<Types.ModerationUsersPostResponse>('POST', `/moderation/users/${params.userId}`, { ...options });
      },
    },
    batch: {
      /**
       * POST /batch/posts/delete
       */
      async createDelete(options?: RequestOptions): Promise<ApiResponse<Types.BatchPostsDeletePostResponse>> {
        return request<Types.BatchPostsDeletePostResponse>('POST', '/batch/posts/delete', { ...options });
      },
      /**
       * POST /batch/posts/update
       */
      async createUpdate(options?: RequestOptions): Promise<ApiResponse<Types.BatchPostsUpdatePostResponse>> {
        return request<Types.BatchPostsUpdatePostResponse>('POST', '/batch/posts/update', { ...options });
      },
      /**
       * POST /batch/posts/action
       */
      async createAction(options?: RequestOptions): Promise<ApiResponse<Types.BatchPostsActionPostResponse>> {
        return request<Types.BatchPostsActionPostResponse>('POST', '/batch/posts/action', { ...options });
      },
    },
    webhooks: {
      /**
       * GET /webhooks
       */
      async list(options?: RequestOptions): Promise<ApiResponse<Types.WebhooksGetResponse>> {
        return request<Types.WebhooksGetResponse>('GET', '/webhooks', { ...options });
      },
      /**
       * POST /webhooks
       */
      async create(options?: RequestOptions): Promise<ApiResponse<unknown>> {
        return request<unknown>('POST', '/webhooks', { ...options });
      },
      /**
       * GET /webhooks/:id
       */
      async getWebhooks(params: Types.WebhooksGetParams, options?: RequestOptions): Promise<ApiResponse<Types.WebhooksGetResponse>> {
        return request<Types.WebhooksGetResponse>('GET', `/webhooks/${params.id}`, { ...options });
      },
      /**
       * DELETE /webhooks/:id
       */
      async deleteWebhooks(params: Types.WebhooksDeleteParams, options?: RequestOptions): Promise<ApiResponse<Types.WebhooksDeleteResponse>> {
        return request<Types.WebhooksDeleteResponse>('DELETE', `/webhooks/${params.id}`, { ...options });
      },
      /**
       * POST /webhooks/:id/test
       */
      async createTest(params: Types.WebhooksTestPostParams, options?: RequestOptions): Promise<ApiResponse<Types.WebhooksTestPostResponse>> {
        return request<Types.WebhooksTestPostResponse>('POST', `/webhooks/${params.id}/test`, { ...options });
      },
    },
    files: {
      /**
       * POST /files/presigned-url
       */
      async createPresigned-url(options?: RequestOptions): Promise<ApiResponse<Types.FilesPresigned-urlPostResponse>> {
        return request<Types.FilesPresigned-urlPostResponse>('POST', '/files/presigned-url', { ...options });
      },
      /**
       * GET /files/:id
       */
      async getFiles(params: Types.FilesGetParams, options?: RequestOptions): Promise<ApiResponse<Types.FilesGetResponse>> {
        return request<Types.FilesGetResponse>('GET', `/files/${params.id}`, { ...options });
      },
      /**
       * DELETE /files/:id
       */
      async deleteFiles(params: Types.FilesDeleteParams, options?: RequestOptions): Promise<ApiResponse<Types.FilesDeleteResponse>> {
        return request<Types.FilesDeleteResponse>('DELETE', `/files/${params.id}`, { ...options });
      },
    },
    analytics: {
      /**
       * POST /analytics/query
       */
      async createQuery(options?: RequestOptions): Promise<ApiResponse<Types.AnalyticsQueryPostResponse>> {
        return request<Types.AnalyticsQueryPostResponse>('POST', '/analytics/query', { ...options });
      },
    },
    api-keys: {
      /**
       * GET /api-keys
       */
      async list(options?: RequestOptions): Promise<ApiResponse<Types.Api-keysGetResponse>> {
        return request<Types.Api-keysGetResponse>('GET', '/api-keys', { ...options });
      },
      /**
       * POST /api-keys
       */
      async create(options?: RequestOptions): Promise<ApiResponse<unknown>> {
        return request<unknown>('POST', '/api-keys', { ...options });
      },
      /**
       * DELETE /api-keys/:id
       */
      async deleteApi-keys(params: Types.Api-keysDeleteParams, options?: RequestOptions): Promise<ApiResponse<Types.Api-keysDeleteResponse>> {
        return request<Types.Api-keysDeleteResponse>('DELETE', `/api-keys/${params.id}`, { ...options });
      },
      /**
       * POST /api-keys/:id/rotate
       */
      async createRotate(params: Types.Api-keysRotatePostParams, options?: RequestOptions): Promise<ApiResponse<Types.Api-keysRotatePostResponse>> {
        return request<Types.Api-keysRotatePostResponse>('POST', `/api-keys/${params.id}/rotate`, { ...options });
      },
    },
    schemas: {
      /**
       * GET /schemas
       */
      async list(options?: RequestOptions): Promise<ApiResponse<Types.SchemasGetResponse>> {
        return request<Types.SchemasGetResponse>('GET', '/schemas', { ...options });
      },
    },
  };
}

export type Client = ReturnType<typeof createClient>;