/**
 * Auto-generated API Client
 * Generated by dhi-sdk from Hono app
 */

import type * as Types from './types';

export interface ClientConfig {
  baseUrl: string;
  headers?: Record<string, string>;
  fetch?: typeof fetch;
}

export interface RequestOptions {
  headers?: Record<string, string>;
  signal?: AbortSignal;
}

export interface ApiResponse<T> {
  data: T;
  status: number;
  headers: Headers;
}

export class ApiError extends Error {
  constructor(
    public status: number,
    public statusText: string,
    public body: unknown
  ) {
    super(`API Error: ${status} ${statusText}`);
    this.name = 'ApiError';
  }
}

export function createClient(config: ClientConfig) {
  const baseUrl = config.baseUrl.replace(/\/$/, '');
  const defaultHeaders = config.headers || {};
  const fetchFn = config.fetch || fetch;

  async function request<T>(
    method: string,
    path: string,
    options: {
      body?: unknown;
      query?: Record<string, string | number | boolean | undefined>;
      headers?: Record<string, string>;
      signal?: AbortSignal;
    } = {}
  ): Promise<ApiResponse<T>> {
    const url = new URL(baseUrl + path);

    if (options.query) {
      for (const [key, value] of Object.entries(options.query)) {
        if (value !== undefined) {
          url.searchParams.set(key, String(value));
        }
      }
    }

    const response = await fetchFn(url.toString(), {
      method,
      headers: {
        'Content-Type': 'application/json',
        ...defaultHeaders,
        ...options.headers,
      },
      body: options.body ? JSON.stringify(options.body) : undefined,
      signal: options.signal,
    });

    if (!response.ok) {
      const body = await response.text().catch(() => null);
      throw new ApiError(response.status, response.statusText, body);
    }

    const data = await response.json() as T;
    return { data, status: response.status, headers: response.headers };
  }

  return {
    root: {
      /**
       * GET /
       */
      async listIndex(options?: RequestOptions): Promise<ApiResponse<Types.GetResponse>> {
        return request<Types.GetResponse>('GET', '/', { ...options });
      },
    },
    api: {
      /**
       * GET /api/users
       */
      async listUsers(options?: RequestOptions): Promise<ApiResponse<Types.ApiUsersGetResponse>> {
        return request<Types.ApiUsersGetResponse>('GET', '/api/users', { ...options });
      },
      /**
       * POST /api/users
       */
      async createUsers(options?: RequestOptions): Promise<ApiResponse<unknown>> {
        return request<unknown>('POST', '/api/users', { ...options });
      },
      /**
       * GET /api/users/:id
       */
      async getUsers(params: Types.ApiUsersGetParams, options?: RequestOptions): Promise<ApiResponse<Types.ApiUsersGetResponse>> {
        return request<Types.ApiUsersGetResponse>('GET', `/api/users/${params.id}`, { ...options });
      },
      /**
       * PUT /api/users/:id
       */
      async updateUsers(params: Types.ApiUsersPutParams, options?: RequestOptions): Promise<ApiResponse<Types.ApiUsersPutResponse>> {
        return request<Types.ApiUsersPutResponse>('PUT', `/api/users/${params.id}`, { ...options });
      },
      /**
       * DELETE /api/users/:id
       */
      async deleteUsers(params: Types.ApiUsersDeleteParams, options?: RequestOptions): Promise<ApiResponse<Types.ApiUsersDeleteResponse>> {
        return request<Types.ApiUsersDeleteResponse>('DELETE', `/api/users/${params.id}`, { ...options });
      },
      /**
       * POST /api/products
       */
      async createProducts(options?: RequestOptions): Promise<ApiResponse<unknown>> {
        return request<unknown>('POST', '/api/products', { ...options });
      },
      /**
       * POST /api/orders
       */
      async createOrders(options?: RequestOptions): Promise<ApiResponse<unknown>> {
        return request<unknown>('POST', '/api/orders', { ...options });
      },
      /**
       * GET /api/schema/:name
       */
      async getSchema(params: Types.ApiSchemaGetParams, options?: RequestOptions): Promise<ApiResponse<unknown>> {
        return request<unknown>('GET', `/api/schema/${params.name}`, { ...options });
      },
      /**
       * GET /api/schemas
       */
      async listSchemas(options?: RequestOptions): Promise<ApiResponse<unknown>> {
        return request<unknown>('GET', '/api/schemas', { ...options });
      },
    },
  };
}

export type Client = ReturnType<typeof createClient>;