/**
 * Auto-generated TypeScript types
 * Generated by dhi-sdk from Hono app
 */

export interface GetResponse {
  [key: string]: unknown;
}
export interface ApiUsersGetResponse {
  [key: string]: unknown;
}
export interface ApiUsersGetParams {
  id: string;
}
export interface ApiUsersPutResponse {
  [key: string]: unknown;
}
export interface ApiUsersPutParams {
  id: string;
}
export interface ApiUsersDeleteResponse {
  [key: string]: unknown;
}
export interface ApiUsersDeleteParams {
  id: string;
}
export interface ApiSchemaGetParams {
  name: string;
}
export interface CreateUserSchema {
  name: string;
  email: string;
  age?: number;
  role: unknown;
}
export interface UpdateUserSchema {
  name?: string;
  email?: string;
  age?: number;
  role: unknown;
}
export interface ListUsersQuerySchema {
  page: string;
  limit: string;
  role: unknown;
}
export interface ProductSchema {
  name: string;
  price: number;
  quantity: number;
  tags?: unknown[];
}
export interface OrderSchema {
  userId: string;
  items: unknown[];
  productId: string;
  quantity: number;
  shippingAddress: Record<string, unknown>;
  street: string;
  city: string;
  zipCode: string;
  country: string;
}
