import type { ParsedType, ParsedProperty, ImportInfo } from "./parser.js";

const TYPE_MAPPING: Record<string, string> = {
  number: "z.number()",
  string: "z.string()",
  boolean: "z.boolean()",
  bigint: "z.bigint()",
  Date: "z.date()",
  any: "z.any()",
  unknown: "z.unknown()",
  void: "z.void()",
  null: "z.null()",
  undefined: "z.undefined()",
};

/**
 * Generate dhi schema code from parsed types
 */
export function generateDhiSchema(types: ParsedType[], imports?: ImportInfo[]): string {
  const lines: string[] = [
    "// Auto-generated by ts-to-dhi",
    "// Do not edit manually",
    "",
    "import { z } from 'dhi';",
    "",
  ];

  // Handle external imports
  if (imports && imports.length > 0) {
    const externalImports = imports.filter(i => !i.isTypeOnly);
    if (externalImports.length > 0) {
      lines.push("// External types (will use z.any() as placeholder)");
      for (const imp of externalImports) {
        lines.push(`const ${imp.name}Schema = z.any(); // From: ${imp.source}`);
      }
      lines.push("");
    }
  }

  for (const type of types) {
    // Handle non-object types (tuples, intersections, primitives)
    if (type.rawType && type.properties.length === 0) {
      const schema = typeToDhiSchema(type.rawType, imports);
      lines.push(`export const ${type.name}Schema = ${schema};`);
      lines.push("");
      lines.push(`export type ${type.name} = z.infer<typeof ${type.name}Schema>;`);
      lines.push("");
      continue;
    }

    if (type.properties.length === 0) {
      // Skip empty types
      continue;
    }

    lines.push(`export const ${type.name}Schema = z.object({`);

    for (const prop of type.properties) {
      // Method signatures: foo(): type -> skip with comment
      if (prop.type.includes("=>")) {
        lines.push(`  // ${prop.name}: ${prop.type} (method - validation skipped),`);
        continue;
      }

      // Index signature: [key: string] -> use .catchall() for additional properties
      if (prop.name.startsWith("[key:")) {
        // Index signatures become .catchall() which allows arbitrary keys
        const schema = typeToDhiSchema(prop.type.replace(/^Record<[^,]+,\s*/, "").replace(/>$/, ""), imports);
        lines.push(`  // Index signature: ${prop.name}`);
        lines.push(`  // .catchall(${schema}) would go here but dhi doesn't support it directly`);
        lines.push(`  // Consider using z.record() for this type instead`);
        continue;
      }
      
      // Skip generic type parameters (like T in ApiResponse<T>)
      if (/^[A-Z]$/i.test(prop.type) && !TYPE_MAPPING[prop.type.toLowerCase()]) {
        lines.push(`  // ${prop.name}: ${prop.type} (generic parameter - needs manual implementation),`);
        continue;
      }
      
      const schema = propertyToDhiSchema(prop, imports);
      lines.push(`  ${prop.name}: ${schema},`);
    }

    lines.push("});");
    lines.push("");
    lines.push(`export type ${type.name} = z.infer<typeof ${type.name}Schema>;`);
    lines.push("");
  }

  return lines.join("\n");
}

/**
 * Convert a parsed property to dhi schema
 */
function propertyToDhiSchema(prop: ParsedProperty, imports?: ImportInfo[]): string {
  let schema = typeToDhiSchema(prop.type, imports);

  // Apply JSDoc validators
  if (prop.jsDoc) {
    const { jsDoc } = prop;
    
    // Number validators
    if (jsDoc.minimum !== undefined) {
      schema = `${schema}.min(${jsDoc.minimum})`;
    }
    if (jsDoc.maximum !== undefined) {
      schema = `${schema}.max(${jsDoc.maximum})`;
    }
    
    // String validators
    if (jsDoc.minLength !== undefined) {
      schema = `${schema}.min(${jsDoc.minLength})`;
    }
    if (jsDoc.maxLength !== undefined) {
      schema = `${schema}.max(${jsDoc.maxLength})`;
    }
    if (jsDoc.format) {
      // Map format to dhi validators
      switch (jsDoc.format) {
        case "email":
          schema = schema.replace("z.string()", "z.string().email()");
          break;
        case "uuid":
          schema = schema.replace("z.string()", "z.string().uuid()");
          break;
        case "url":
          schema = schema.replace("z.string()", "z.string().url()");
          break;
        default:
          // For unknown formats, add a comment
          break;
      }
    }
    if (jsDoc.pattern) {
      schema = `${schema}.regex(/${jsDoc.pattern}/)`;
    }
    
    // Default value
    if (jsDoc.default !== undefined) {
      const defaultVal = typeof jsDoc.default === "string" 
        ? `"${jsDoc.default}"` 
        : String(jsDoc.default);
      schema = `${schema}.default(${defaultVal})`;
    }
    
    // Description (as metadata, not validator)
    if (jsDoc.description) {
      // Could add .describe() if dhi supports it
    }
  }

  if (prop.optional) {
    schema = `${schema}.optional()`;
  }
  if (prop.nullable) {
    schema = `${schema}.nullable()`;
  }

  return schema;
}

/**
 * Convert TypeScript type string to dhi schema
 */
function typeToDhiSchema(tsType: string, imports?: ImportInfo[]): string {
  // Handle tuple types [string, number]
  if (tsType.startsWith("[") && tsType.endsWith("]")) {
    const inner = tsType.slice(1, -1).trim();
    if (!inner) return "z.tuple([])";
    
    // Handle rest elements (...T[])
    if (inner.includes("...")) {
      // For simplicity, convert rest tuple to array
      return "z.array(z.any())";
    }
    
    const elements = inner.split(",").map(s => s.trim()).filter(Boolean);
    const schemas = elements.map(e => typeToDhiSchema(e, imports));
    return `z.tuple([${schemas.join(", ")}])`;
  }

  // Handle array types (string[] or Array<T>)
  if (tsType.endsWith("[]")) {
    const elemType = tsType.slice(0, -2);
    return `z.array(${typeToDhiSchema(elemType, imports)})`;
  }
  if (tsType.startsWith("Array<") && tsType.endsWith(">")) {
    const elemType = tsType.slice(6, -1);
    return `z.array(${typeToDhiSchema(elemType, imports)})`;
  }

  // Handle intersection types (A & B)
  if (tsType.includes(" & ")) {
    const parts = tsType.split(" & ").map(p => p.trim()).filter(Boolean);
    return `z.intersection([${parts.map(p => typeToDhiSchema(p, imports)).join(", ")}])`;
  }

  // Handle union types
  if (tsType.includes(" | ")) {
    const parts = tsType.split(" | ").map((p) => p.trim()).filter(p => p);
    const nonNullParts = parts.filter(p => p !== "null" && p !== "undefined");
    
    // Single non-null type with null → just the type (null handled by nullable flag)
    if (nonNullParts.length === 1) {
      return typeToDhiSchema(nonNullParts[0], imports);
    }
    
    // String literal union → z.enum()
    if (nonNullParts.every((p) => p.startsWith('"') || p.startsWith("'"))) {
      const values = nonNullParts.map((p) => p.replace(/["']/g, ""));
      return `z.enum([${values.map((v) => `"${v}"`).join(", ")}])`;
    }
    
    // Mixed union → z.union()
    return `z.union([${nonNullParts.map((p) => typeToDhiSchema(p, imports)).join(", ")}])`;
  }

  // Handle literal types
  if (tsType.startsWith('"') || tsType.startsWith("'")) {
    return `z.literal(${tsType})`;
  }
  if (tsType === "true" || tsType === "false") {
    return `z.literal(${tsType})`;
  }

  // Handle Record<K, V>
  if (tsType.startsWith("Record<") && tsType.endsWith(">")) {
    const match = tsType.match(/Record<\s*[^,]+\s*,\s*([^>]+)\s*>/);
    if (match) {
      const valueType = typeToDhiSchema(match[1].trim(), imports);
      return `z.record(${valueType})`;
    }
    return "z.record(z.any())";
  }

  // Basic types
  if (TYPE_MAPPING[tsType]) {
    return TYPE_MAPPING[tsType];
  }

  // Reference to another type - check if it's an import first
  const baseName = tsType.split("<")[0];
  const isImport = imports?.some(i => i.name === baseName);
  
  if (isImport) {
    return `${baseName}Schema`;
  }
  
  // Otherwise assume it's defined in the same file
  return `${baseName}Schema`;
}
