import type { ParsedType, ParsedProperty } from "./parser.js";

const TYPE_MAPPING: Record<string, string> = {
  number: "z.number()",
  string: "z.string()",
  boolean: "z.boolean()",
  bigint: "z.bigint()",
  Date: "z.date()",
  any: "z.any()",
  unknown: "z.unknown()",
  void: "z.void()",
  null: "z.null()",
  undefined: "z.undefined()",
};

/**
 * Generate dhi schema code from parsed types
 */
/**
 * Generate dhi schema code from parsed types
 */
/**
 * Generate dhi schema code from parsed types
 */
/**
 * Generate dhi schema code from parsed types
 */
export function generateDhiSchema(types: ParsedType[]): string {
  const lines: string[] = [
    "// Auto-generated by ts-to-dhi",
    "// Do not edit manually",
    "",
    "import { z } from 'dhi';",
    "",
  ];

  for (const type of types) {
    // Handle non-object types (tuples, intersections, primitives)
    if (type.rawType && type.properties.length === 0) {
      const schema = typeToDhiSchema(type.rawType);
      lines.push(`export const ${type.name}Schema = ${schema};`);
      lines.push("");
      lines.push(`export type ${type.name} = z.infer<typeof ${type.name}Schema>;`);
      lines.push("");
      continue;
    }

    // Separate regular properties from inheritance (__extends_*)
    const regularProps = type.properties.filter(p => !p.name.startsWith("__extends_"));
    const extendsProps = type.properties.filter(p => p.name.startsWith("__extends_"));
    
    // Handle empty interfaces (no regular properties, no extends)
    if (regularProps.length === 0 && extendsProps.length === 0) {
      lines.push(`export const ${type.name}Schema = z.object({});`);
      lines.push("");
      lines.push(`export type ${type.name} = z.infer<typeof ${type.name}Schema>;`);
      lines.push("");
      continue;
    }
    
    // Build the base object schema
    const objectSchemaLines: string[] = [];
    objectSchemaLines.push("z.object({");
    
    for (const prop of regularProps) {
      // Method signatures: foo(): type -> skip with comment
      if (prop.type.includes("=>")) {
        objectSchemaLines.push(`  // ${prop.name}: ${prop.type} (method - validation skipped),`);
        continue;
      }

      // Index signature: [key: string] -> use .catchall() for additional properties
      if (prop.name.startsWith("[key:")) {
        // Index signatures become .catchall() which allows arbitrary keys
        const schema = typeToDhiSchema(prop.type.replace(/^Record<[^,]+,\s*/, "").replace(/>$/, ""));
        objectSchemaLines.push(`  // Index signature: ${prop.name}`);
        objectSchemaLines.push(`  // .catchall(${schema}) would go here but dhi doesn't support it directly`);
        objectSchemaLines.push(`  // Consider using z.record() for this type instead`);
        continue;
      }
      
      // Skip generic type parameters (like T in ApiResponse<T>)
      if (/^[A-Z]$/i.test(prop.type) && !TYPE_MAPPING[prop.type.toLowerCase()]) {
        objectSchemaLines.push(`  // ${prop.name}: ${prop.type} (generic parameter - needs manual implementation),`);
        continue;
      }
      
      // Handle __GENERIC_* markers from parser (generic type references like data: T)
      if (prop.type.startsWith("__GENERIC_")) {
        const genericName = prop.type.replace("__GENERIC_", "");
        objectSchemaLines.push(`  // ${prop.name}: ${genericName} (generic parameter - needs manual implementation),`);
        continue;
      }
      
      const schema = propertyToDhiSchema(prop);
      objectSchemaLines.push(`  ${prop.name}: ${schema},`);
    }
    
    objectSchemaLines.push("})");
    const objectSchema = objectSchemaLines.join("\n");
    
    // If there are extended types, use z.intersection()
    if (extendsProps.length > 0) {
      const extendedSchemas = extendsProps.map(p => `${p.type}Schema`);
      lines.push(`export const ${type.name}Schema = z.intersection([`);
      lines.push(`  ${extendedSchemas.join(", ")},`);
      lines.push(`  ${objectSchema}`);
      lines.push(`]);`);
    } else {
      lines.push(`export const ${type.name}Schema = ${objectSchema};`);
    }
    
    lines.push("");
    lines.push(`export type ${type.name} = z.infer<typeof ${type.name}Schema>;`);
    lines.push("");
  }

  return lines.join("\n");
}

/**
 * Convert a parsed property to dhi schema
 */
function propertyToDhiSchema(prop: ParsedProperty): string {
  let schema = typeToDhiSchema(prop.type);

  if (prop.optional) {
    schema = `${schema}.optional()`;
  }
  if (prop.nullable) {
    schema = `${schema}.nullable()`;
  }

  return schema;
}

/**
 * Convert TypeScript type string to dhi schema
 */
/**
 * Convert TypeScript type string to dhi schema
 */
function typeToDhiSchema(tsType: string): string {
  // Handle generic type references (from parser's __GENERIC_* marker)
  if (tsType.startsWith("__GENERIC_")) {
    return "z.any() /* generic type - manual implementation needed */";
  }
  
  // Handle tuple types [string, number]
  if (tsType.startsWith("[") && tsType.endsWith("]")) {
    const inner = tsType.slice(1, -1).trim();
    if (!inner) return "z.tuple([])";
    
    // Handle rest elements (...T[])
    if (inner.includes("...")) {
      // For simplicity, convert rest tuple to array
      return "z.array(z.any())";
    }
    
    const elements = inner.split(",").map(s => s.trim()).filter(Boolean);
    const schemas = elements.map(typeToDhiSchema);
    return `z.tuple([${schemas.join(", ")}])`;
  }

  // Handle array types (string[] or Array<T>)
  if (tsType.endsWith("[]")) {
    const elemType = tsType.slice(0, -2);
    return `z.array(${typeToDhiSchema(elemType)})`;
  }
  if (tsType.startsWith("Array<") && tsType.endsWith(">")) {
    const elemType = tsType.slice(6, -1);
    return `z.array(${typeToDhiSchema(elemType)})`;
  }

  // Handle intersection types (A & B)
  if (tsType.includes(" & ")) {
    const parts = tsType.split(" & ").map(p => p.trim()).filter(Boolean);
    return `z.intersection([${parts.map(typeToDhiSchema).join(", ")}])`;
  }

  // Handle union types
  if (tsType.includes(" | ")) {
    const parts = tsType.split(" | ").map((p) => p.trim()).filter(p => p);
    const nonNullParts = parts.filter(p => p !== "null" && p !== "undefined");
    
    // Single non-null type with null → just the type (null handled by nullable flag)
    if (nonNullParts.length === 1) {
      return typeToDhiSchema(nonNullParts[0]);
    }
    
    // String literal union → z.enum()
    if (nonNullParts.every((p) => p.startsWith('"') || p.startsWith("'"))) {
      const values = nonNullParts.map((p) => p.replace(/["']/g, ""));
      return `z.enum([${values.map((v) => `"${v}"`).join(", ")}])`;
    }
    
    // Mixed union → z.union()
    return `z.union([${nonNullParts.map((p) => typeToDhiSchema(p)).join(", ")}])`;
  }

  // Handle literal types (string, number, boolean)
  if (tsType.startsWith('"') || tsType.startsWith("'")) {
    return `z.literal(${tsType})`;
  }
  if (tsType === "true" || tsType === "false") {
    return `z.literal(${tsType})`;
  }
  // Number literals: 1, 2, 3 → z.literal(1)
  if (/^-?\d+(\.\d+)?$/.test(tsType)) {
    return `z.literal(${tsType})`;
  }

  // Handle Record<K, V>
  if (tsType.startsWith("Record<") && tsType.endsWith(">")) {
    const match = tsType.match(/Record<\s*[^,]+\s*,\s*([^>]+)\s*>/);
    if (match) {
      const valueType = typeToDhiSchema(match[1].trim());
      return `z.record(${valueType})`;
    }
    return "z.record(z.any())";
  }

  // Handle inline object types: { a: string; b: number }
  if (tsType.startsWith("{ ") && tsType.endsWith(" }")) {
    const inner = tsType.slice(2, -2).trim(); // Remove { and }
    if (!inner) return "z.object({})";
    
    // Parse properties that may be separated by semicolons or just spaces
    const props = inner.split(";").map(p => p.trim()).filter(Boolean).map(prop => {
      const match = prop.match(/^([^:]+?)(\?)?:\s*(.+)$/);
      if (match) {
        const [, name, optional, typeStr] = match;
        const schema = typeToDhiSchema(typeStr.trim());
        if (optional) {
          return `${name}: ${schema}.optional()`;
        }
        return `${name}: ${schema}`;
      }
      return "";
    }).filter(Boolean).join(", ");
    
    return props ? `z.object({ ${props} })` : "z.object({})";
  }

  // Basic types
  if (TYPE_MAPPING[tsType]) {
    return TYPE_MAPPING[tsType];
  }

  // Reference to another type (strip generics)
  const baseName = tsType.split("<")[0];
  return `${baseName}Schema`;
}
