/**
 * Auto-generated TypeScript types
 * Generated by dhi-sdk from Hono app
 */

export interface GetResponse {
  [key: string]: unknown;
}
export interface HealthGetResponse {
  [key: string]: unknown;
}
export interface AuthLoginPostResponse {
  [key: string]: unknown;
}
export interface AuthRefreshPostResponse {
  [key: string]: unknown;
}
export interface AuthLogoutPostResponse {
  [key: string]: unknown;
}
export interface UsersGetResponse {
  [key: string]: unknown;
}
export interface UsersGetParams {
  id: string;
}
export interface UsersPutResponse {
  [key: string]: unknown;
}
export interface UsersPutParams {
  id: string;
}
export interface UsersDeleteResponse {
  [key: string]: unknown;
}
export interface UsersDeleteParams {
  id: string;
}
export interface UsersPostsGetResponse {
  [key: string]: unknown;
}
export interface UsersPostsGetParams {
  userId: string;
}
export interface UsersPostsPostParams {
  userId: string;
}
export interface UsersPostsPutResponse {
  [key: string]: unknown;
}
export interface UsersPostsPutParams {
  userId: string;
  postId: string;
}
export interface UsersPostsDeleteResponse {
  [key: string]: unknown;
}
export interface UsersPostsDeleteParams {
  userId: string;
  postId: string;
}
export interface UsersPostsActionsPostResponse {
  [key: string]: unknown;
}
export interface UsersPostsActionsPostParams {
  userId: string;
  postId: string;
}
export interface UsersPostsCommentsGetResponse {
  [key: string]: unknown;
}
export interface UsersPostsCommentsGetParams {
  userId: string;
  postId: string;
}
export interface UsersPostsCommentsPostParams {
  userId: string;
  postId: string;
}
export interface UsersPostsCommentsDeleteResponse {
  [key: string]: unknown;
}
export interface UsersPostsCommentsDeleteParams {
  userId: string;
  postId: string;
  commentId: string;
}
export interface ModerationPostsPostResponse {
  [key: string]: unknown;
}
export interface ModerationPostsPostParams {
  postId: string;
}
export interface ModerationCommentsPostResponse {
  [key: string]: unknown;
}
export interface ModerationCommentsPostParams {
  commentId: string;
}
export interface ModerationUsersPostResponse {
  [key: string]: unknown;
}
export interface ModerationUsersPostParams {
  userId: string;
}
export interface BatchPostsDeletePostResponse {
  [key: string]: unknown;
}
export interface BatchPostsUpdatePostResponse {
  [key: string]: unknown;
}
export interface BatchPostsActionPostResponse {
  [key: string]: unknown;
}
export interface WebhooksGetResponse {
  [key: string]: unknown;
}
export interface WebhooksGetParams {
  id: string;
}
export interface WebhooksDeleteResponse {
  [key: string]: unknown;
}
export interface WebhooksDeleteParams {
  id: string;
}
export interface WebhooksTestPostResponse {
  [key: string]: unknown;
}
export interface WebhooksTestPostParams {
  id: string;
}
export interface FilesPresigned-urlPostResponse {
  [key: string]: unknown;
}
export interface FilesGetResponse {
  [key: string]: unknown;
}
export interface FilesGetParams {
  id: string;
}
export interface FilesDeleteResponse {
  [key: string]: unknown;
}
export interface FilesDeleteParams {
  id: string;
}
export interface AnalyticsQueryPostResponse {
  [key: string]: unknown;
}
export interface Api-keysGetResponse {
  [key: string]: unknown;
}
export interface Api-keysDeleteResponse {
  [key: string]: unknown;
}
export interface Api-keysDeleteParams {
  id: string;
}
export interface Api-keysRotatePostResponse {
  [key: string]: unknown;
}
export interface Api-keysRotatePostParams {
  id: string;
}
export interface SchemasGetResponse {
  [key: string]: unknown;
}
export interface LoginSchema {
  email: string;
  password: string;
  mfaCode?: string;
}
export interface RegisterSchema {
  email: string;
  password: string;
  name: string;
  role: unknown;
  profile: Record<string, unknown>;
  bio?: string;
  avatar?: string;
  social: Record<string, unknown>;
  twitter?: string;
  github?: string;
  linkedin?: string;
}
export interface RefreshTokenSchema {
  refreshToken: string;
}
export interface UpdateUserSchema {
  name?: string;
  email: boolean;
  profile: Record<string, unknown>;
  bio?: string;
  avatar?: string;
  settings: Record<string, unknown>;
  notifications: Record<string, unknown>;
  push: boolean;
  sms: boolean;
  privacy: Record<string, unknown>;
  profilePublic: boolean;
  showEmail: boolean;
  theme: unknown;
}
export interface CreatePostSchema {
  title: string;
  content: string;
  excerpt?: string;
  status: unknown;
  tags?: unknown[];
  metadata: Record<string, unknown>;
  seoTitle?: string;
  seoDescription?: string;
  canonicalUrl?: string;
  scheduledAt?: string;
}
export interface CreateCommentSchema {
  content: string;
  parentId?: string;
}
export interface ListQuerySchema {
  page: unknown;
  limit: unknown;
  sortBy?: string;
  sortOrder: unknown;
  search?: string;
}
export type PostQuerySchema = string;
export interface PostActionSchema {
  action: unknown;
  scheduledAt?: string;
  reason: string;
  position: number;
  duration: number;
  newOwnerId: string;
  keepOriginalAuthor: boolean;
}
export interface ModerationActionSchema {
  action: unknown;
  reason: string;
  details?: string;
  notifyUser: boolean;
  message: string;
  severity: unknown;
  duration?: number;
  scope: unknown;
  notes?: string;
}
export interface BatchDeleteSchema {
  ids: unknown[];
  hardDelete: boolean;
}
export interface BatchUpdateSchema {
  ids: unknown[];
}
export interface BatchActionSchema {
  ids: unknown[];
}
export interface WebhookCreateSchema {
  url: string;
  events: unknown[];
  secret?: string;
  metadata?: unknown;
}
export interface FileUploadMetadataSchema {
  filename: string;
  contentType: string;
  size: number;
  purpose: unknown;
  metadata?: unknown;
}
export interface AnalyticsQuerySchema {
  metrics: unknown[];
  groupBy: unknown;
  dateFrom: string;
  dateTo: string;
  filters: Record<string, unknown>;
  postIds?: unknown[];
  tags?: unknown[];
  status: unknown;
}
export interface CreateApiKeySchema {
  name: string;
  scopes: unknown[];
  expiresAt?: string;
  rateLimit: Record<string, unknown>;
  requests: number;
  window: unknown;
}
